# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n\x0b\x45\x63hoMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"X\n\rRandomRequest\x12\x14\n\x07numbers\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x0b\n\x03min\x18\x02 \x01(\r\x12\x10\n\x03max\x18\x03 \x01(\rH\x01\x88\x01\x01\x42\n\n\x08_numbersB\x06\n\x04_max\"\x1f\n\x0eRandomResponse\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x98\x01\n\x0e\x45xampleService\x12%\n\x07GetEcho\x12\x0c.EchoMessage\x1a\x0c.EchoMessage\x12.\n\tGetRandom\x12\x0e.RandomRequest\x1a\x0f.RandomResponse0\x01\x12/\n\rStreamingEcho\x12\x0c.EchoMessage\x1a\x0c.EchoMessage(\x01\x30\x01\x42,\n(es.unex.giiis.aos.grpc.example.generatedP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(es.unex.giiis.aos.grpc.example.generatedP\001'
  _globals['_ECHOMESSAGE']._serialized_start=50
  _globals['_ECHOMESSAGE']._serialized_end=80
  _globals['_RANDOMREQUEST']._serialized_start=82
  _globals['_RANDOMREQUEST']._serialized_end=170
  _globals['_RANDOMRESPONSE']._serialized_start=172
  _globals['_RANDOMRESPONSE']._serialized_end=203
  _globals['_EXAMPLESERVICE']._serialized_start=206
  _globals['_EXAMPLESERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
