# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import example_pb2 as example__pb2


class ExampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEcho = channel.unary_unary(
                '/ExampleService/GetEcho',
                request_serializer=example__pb2.EchoMessage.SerializeToString,
                response_deserializer=example__pb2.EchoMessage.FromString,
                )
        self.GetRandom = channel.unary_stream(
                '/ExampleService/GetRandom',
                request_serializer=example__pb2.RandomRequest.SerializeToString,
                response_deserializer=example__pb2.RandomResponse.FromString,
                )
        self.StreamingEcho = channel.stream_stream(
                '/ExampleService/StreamingEcho',
                request_serializer=example__pb2.EchoMessage.SerializeToString,
                response_deserializer=example__pb2.EchoMessage.FromString,
                )


class ExampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingEcho(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEcho,
                    request_deserializer=example__pb2.EchoMessage.FromString,
                    response_serializer=example__pb2.EchoMessage.SerializeToString,
            ),
            'GetRandom': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRandom,
                    request_deserializer=example__pb2.RandomRequest.FromString,
                    response_serializer=example__pb2.RandomResponse.SerializeToString,
            ),
            'StreamingEcho': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingEcho,
                    request_deserializer=example__pb2.EchoMessage.FromString,
                    response_serializer=example__pb2.EchoMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExampleService/GetEcho',
            example__pb2.EchoMessage.SerializeToString,
            example__pb2.EchoMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ExampleService/GetRandom',
            example__pb2.RandomRequest.SerializeToString,
            example__pb2.RandomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingEcho(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ExampleService/StreamingEcho',
            example__pb2.EchoMessage.SerializeToString,
            example__pb2.EchoMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
